version: 2.1
commands:
  print_pipeline_id:
    description: "Printing workflow Id"
    steps:
      - run: echo $CIRCLE_WORKFLOW_ID
jobs:
  printing_from_a_command:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - print_pipeline_id

workflows:
    wf:
      jobs:
        - printing_from_a_command
