version: 2.1
jobs:
  print_hello:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - run:
          name: Print hello to the console
          command: |
            echo 'Hello'
  print_world:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - run:
          name: Print world to the console
          command: |
            echo 'World'
  print_udacity_name:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - run:
          name: Print my name
          command: |
            echo << udacity >>
workflows:
  welcome:
    jobs:
      - print_hello
      - print_world:
          requires: [print_hello]
      - print_udacity_name
