version: 2.1
jobs:
  save_hello_world_output:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - run:
          name: print hello world to file
          command: |
            mkdir target
            cd target
            echo 'Hello World' > output.txt
      - persist_to_workspace:
          root: /tmp/workspace
          paths:
            - target/output.txt
  print_output_file:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - attach_workspace:
          at: /target
      - run:
          name: Print file contents to the console
          command: |
            cat output.txt
workflows:
  welcome:
    jobs:
      - save_hello_world_output
      - print_output_file:
          requires: [save_hello_world_output]
